load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library","cc_import")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "log",
    srcs = glob([
        "*.c",
        "*.cpp",
        "*.cc",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    visibility = [
        "//visibility:public",
    ],
    copts= [],
    deps = [],
)
 
